<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>iLab Policies</title>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">

  <style>
    /* General Reset */
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: 'Poppins', sans-serif;
    }

    body {
      background-color: #f4f4f4;
      color: #333;
    }

    a {
      text-decoration: none;
      color: inherit;
    }

    /* Container */
    .container {
      max-width: 1000px;
      margin: 0 auto;
      padding: 20px;
    }

    /* Breadcrumb */
    .breadcrumb-container {
      padding: 10px 0;
    }

    .breadcrumb-container nav {
      font-size: 14px;
      color: #6c757d;
    }

    .breadcrumb-container nav a {
      color: #007bff;
    }

    /* Page Title */
    .page-title {
      text-align: center;
      padding: 20px 0 10px;
    }

    .page-title h1 {
      font-size: 24px;
      color: #333;
      font-weight: 600;
    }

    /* Policy Categories */
    .policy-categories {
      display: flex;
      justify-content: center;
      padding: 12px 0;
    }

    .category-btn {
      background-color: #e0e0e0;
      border: none;
      padding: 10px 20px;
      border-radius: 20px;
      cursor: pointer;
      color: #333;
      font-weight: 500;
    }

    .category-btn.active,
    .category-btn:hover {
      background-color: darkblue;
      color: #fff;
    }

    /* Policies List */
    .policies-list {
      list-style-type: none;
      padding: 0;
    }

    .policies-list li {
      padding: 15px;
      margin: 10px 0;
      border-radius: 8px;
    }

    .policies-list h3 {
      font-size: 18px;
      font-weight: 600;
      margin-bottom: 5px;
    }

    .policies-list p {
      font-size: 14px;
      color: #666;
      font-weight: 400;
    }

    /* Hide Policies */
    .hidden {
      display: none;
    }
  </style>
</head>
<body>



  <div class="container">
    <!-- Breadcrumb -->
    <header class="breadcrumb-container">
      <nav>
        <a href="/" style="color:darkblue">Home</a> / <span>Policies</span>
      </nav>
    </header>


    <!-- Page Title and Description -->
    <section class="page-title">
      <h1>Explore iLab's policies and guidelines to ensure a safe and productive environment.</h1>
    </section>

    <!-- Policy Categories -->
    <div class="policy-categories">
      <button class="category-btn active" onclick="showPolicies('all')">All Policies</button>
      <button class="category-btn" onclick="showPolicies('General')">General Provisions</button>
      <button class="category-btn" onclick="showPolicies('Bonus')">Bonus Policy</button>
      <button class="category-btn" onclick="showPolicies('Finder')">Finder’s Fee Policy</button>
      <button class="category-btn" onclick="showPolicies('Payment')">Payment of Bonus and Finder’s Fee</button>
      <button class="category-btn" onclick="showPolicies('Final')">Final Clause</button>
    </div>

    <!-- Policies List -->
    <ul id="all-policies" class="policies-list">
    <li>
  <h3>General Provisions</h3>
  <li>1.1 The rationale behind this policy is to encourage and reward staff and/or student assistants who bring in business to the department. It may also reward timely delivery of projects/contracts and/or providing support to projects not directly considered as part of their job description.</li>
  <li>1.2 The policy is also a way to provide an incentive, to reward initiative, and to increase morale, as well as make everybody share in the revenue that they generate. It encourages employees to actively seek business and deliver high-quality work.</li>
  <li>1.3 Members of research staff may be allowed to claim for teaching done, as this may be considered outside of their normal duties.</p>
</li>

<li>
  <h3>Bonus Policy</h3>
  <li>2.1 Bonuses will relate to an individual project/contract.</li>
  <li>2.2 Bonuses should be supported by the income earned by a given project as shown in the relevant project budget. Budgets should be approved by the Director of @iLabAfrica before submitting them to clients.</li>
  <li>2.3 Any project should, at least, bring a 30% surplus (after computing any bonus); otherwise, no bonus can be claimed. (Surplus: Income generated by the project less direct expenses to the project).</li>
  <li>2.4 The bonus is computed as a percentage of the surplus earned (before computing bonuses).</li>
  <li>2.5 The maximum bonus payable will not exceed 9% of the surplus. This might be computed as follows:</li>
    <li>2.5.1 Up to 6% of the bonus goes to the manager: i.e., the staff member bringing in the new project if they also manage its execution.</li>
    <li>2.5.2 Up to 3% of the bonus goes to the person directly managing the tasks of the new project.</li>
    <li>2.5.3 A bonus may also be divided across the team members who have been directly involved in the execution of the project.</li>
    <li>2.5.4 The above percentages may be changed at the discretion of the Director of @iLabAfrica following a relevant proposal by the project manager. However, the maximum bonus will never exceed 6% for any individual, and the total bonuses given will not exceed 9%.</li>
    <li>2.5.5 Some members of staff in lower cadres (e.g., lab assistants, research scholars, interns, secretaries, receptionists) may be paid a small flat amount (not a bonus) for their services provided while executing a project, such as photography, lab assistance, ushering, or general admin of the activity.</li>
</li>

<li>
    <h3>Finder’s Fee Policy</h3>
    <ul>
        <li>3.1 A finder’s fee recognizes the value of somebody introducing business to @iLabAfrica.</li>
        <li>3.2 Finder fees may be paid in some cases, such as:
            <ul>
                <li>3.2.1 A person brings a business opportunity, but they are not involved thereafter.</li>
                <li>3.2.2 A person helps prepare a tender document or research proposal that is successful but is not involved in its implementation (e.g., they support another team).</li>
            </ul>
        </li>
        <li>3.3 The finder’s fee may vary widely, and it is difficult to provide a percentage that will fit all situations.</li>
        <li>3.4 As an initial guideline, for internal collaborations (i.e., a member of a team provides a business opportunity to another team, or a team supports another in proposal writing), a maximum of 2.5% bonus of the value of the business may be given.</li>
        <li>3.5 A finder’s fee should be included when preparing the budget of a project and must be approved by the Director of @iLabAfrica before submission to the client.</li>
    </ul>
</li>

<li>
    <h3>Payment of Bonus and Finder’s Fee</h3>
    <ul>
        <li>4.1 The above policy provides guidelines, but bonuses should never be considered a right of the employee.</li>
        <li>4.2 Payment of a bonus would be subject to achievement of individual performance targets. Staff should agree with the Director, or the person designated by him, on their individual PKI at the beginning of each quarter.</li>
        <li>4.3 The @iLabAfrica Director, at his discretion, makes the final decision on bonus payments.</li>
        <li>4.4 Bonuses are only paid AFTER all income from the project has been received and AFTER the project has been successfully completed.</li>
        <li>4.5 Bonus payments should be included in the budget presented to the Director of @iLabAfrica and approved BEFORE the client is given a quotation.</li>
    </ul>
</li>
<li>
    <h3>Final Clause</h3>
    <l>5.1 This is a provisional bonus policy, subject to review after six (6) months.</li>
</li>

    </ul>

    <ul id="General-policies" class="policies-list hidden">
      <li>
        <h3>General Provisions</h3>
  <li>1.1 The rationale behind this policy is to encourage and reward staff and/or student assistants who bring in business to the department. It may also reward timely delivery of projects/contracts and/or providing support to projects not directly considered as part of their job description.</li>
  <li>1.2 The policy is also a way to provide an incentive, to reward initiative, and to increase morale, as well as make everybody share in the revenue that they generate. It encourages employees to actively seek business and deliver high-quality work.</li>
  <li>1.3 Members of research staff may be allowed to claim for teaching done, as this may be considered outside of their normal duties.</p>
        <!-- Additional content omitted for brevity -->
      </li>
    </ul>

    <ul id="Bonus-policies" class="policies-list hidden">
      <li>
        <h3>Bonus Policy</h3>
        <li>2.1 Bonuses will relate to an individual project/contract.</li>
  <li>2.2 Bonuses should be supported by the income earned by a given project as shown in the relevant project budget. Budgets should be approved by the Director of @iLabAfrica before submitting them to clients.</li>
  <li>2.3 Any project should, at least, bring a 30% surplus (after computing any bonus); otherwise, no bonus can be claimed. (Surplus: Income generated by the project less direct expenses to the project).</li>
  <li>2.4 The bonus is computed as a percentage of the surplus earned (before computing bonuses).</li>
  <li>2.5 The maximum bonus payable will not exceed 9% of the surplus. This might be computed as follows:</li>
    <li>2.5.1 Up to 6% of the bonus goes to the manager: i.e., the staff member bringing in the new project if they also manage its execution.</li>
    <li>2.5.2 Up to 3% of the bonus goes to the person directly managing the tasks of the new project.</li>
    <li>2.5.3 A bonus may also be divided across the team members who have been directly involved in the execution of the project.</li>
    <li>2.5.4 The above percentages may be changed at the discretion of the Director of @iLabAfrica following a relevant proposal by the project manager. However, the maximum bonus will never exceed 6% for any individual, and the total bonuses given will not exceed 9%.</li>
    <li>2.5.5 Some members of staff in lower cadres (e.g., lab assistants, research scholars, interns, secretaries, receptionists) may be paid a small flat amount (not a bonus) for their services provided while executing a project, such as photography, lab assistance, ushering, or general admin of the activity.</li>
      </li>
    </ul>

    <ul id="Finder-policies" class="policies-list hidden">
    <li>
    <h3>Finder’s Fee Policy</h3>
    <ul>
        <li>3.1 A finder’s fee recognizes the value of somebody introducing business to @iLabAfrica.</li>
        <li>3.2 Finder fees may be paid in some cases, such as:
            <ul>
                <li>3.2.1 A person brings a business opportunity, but they are not involved thereafter.</li>
                <li>3.2.2 A person helps prepare a tender document or research proposal that is successful but is not involved in its implementation (e.g., they support another team).</li>
            </ul>
        </li>
        <li>3.3 The finder’s fee may vary widely, and it is difficult to provide a percentage that will fit all situations.</li>
        <li>3.4 As an initial guideline, for internal collaborations (i.e., a member of a team provides a business opportunity to another team, or a team supports another in proposal writing), a maximum of 2.5% bonus of the value of the business may be given.</li>
        <li>3.5 A finder’s fee should be included when preparing the budget of a project and must be approved by the Director of @iLabAfrica before submission to the client.</li>
    </ul>
</li>

    </ul>

    <ul id="Payment-policies" class="policies-list hidden">
      <li>
        <h3>Payment of Bonus and Finder’s Fee</h3>
        <ul>
        <li>4.1 The above policy provides guidelines, but bonuses should never be considered a right of the employee.</li>
        <li>4.2 Payment of a bonus would be subject to achievement of individual performance targets. Staff should agree with the Director, or the person designated by him, on their individual PKI at the beginning of each quarter.</li>
        <li>4.3 The @iLabAfrica Director, at his discretion, makes the final decision on bonus payments.</li>
        <li>4.4 Bonuses are only paid AFTER all income from the project has been received and AFTER the project has been successfully completed.</li>
        <li>4.5 Bonus payments should be included in the budget presented to the Director of @iLabAfrica and approved BEFORE the client is given a quotation.</li>
    </ul>
      </li>
    </ul>

    <ul id="Final-policies" class="policies-list hidden">
      <li>
        <h3>Final Clause</h3>
        <li>5.1 This is a provisional bonus policy, subject to review after six (6) months</li>
      </li>
    </ul>

  </div>

  <script>
    function showPolicies(category) {
      const allPolicies = document.querySelectorAll('.policies-list');
      const categoryBtns = document.querySelectorAll('.category-btn');

      // Hide all policy lists
      allPolicies.forEach(list => list.classList.add('hidden'));

      // Remove active class from all buttons
      categoryBtns.forEach(btn => btn.classList.remove('active'));

      // Show the selected category and add active class to the button
      document.getElementById(`${category}-policies`).classList.remove('hidden');
      document.querySelector(`.category-btn[onclick="showPolicies('${category}')"]`).classList.add('active');
    }
  </script>
</body>
</html>
